name: Sync Repositories

on:
  push:
    branches:
      - main    
  pull_request:
    branches:
      - main    

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Push to destination repository
      env:
        GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
      run: |
        # Configure git
        git config --global user.name 'src'
        git config --global user.email 'src.action@github.com'
        
        # Get current files
        SOURCE_FILES=$(ls -A | grep -v '.git' | grep -v '.github')
        
        # Clone destination repository
        git clone https://${GITHUB_TOKEN}@github.com/cssh-it/demo1.git
        cd demo1
        
        # Remove existing files (except .git)
        git rm -rf .
        git clean -fdx
        
        # Copy files from source
        cd ..
        rsync -av \
          --exclude='.git' \
          --exclude='.github' \
          ./ demo1/
        
        # Commit and push
        cd demo1
        git add .
        git commit -m "Sync from source repository - Commit: ${GITHUB_SHA}"
        git push origin main