name: Sync Repositories

on:
  push:
    branches:
      - main    
  pull_request:
    branches:
      - main    

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Push to destination repository
      env:
        GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
      run: |
        # Configure git
        git config --global user.name 'src'
        git config --global user.email 'src.action@github.com'
        
        # Clone destination repository
        git clone https://${GITHUB_TOKEN}@github.com/cssh-it/demo1.git
        
        # Clean destination repository
        cd demo1
        rm -rf *  # Remove all files except .git
        cd ..
        
        # Copy files from source to destination
        rsync -av \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='demo1' \
          ./ demo1/
        
        # Commit and push changes
        cd demo1
        git add -A
        git commit -m "Sync from source repository - Commit: ${GITHUB_SHA}" || echo "No changes to commit"
        git push origin main