name: Sync Repositories

on:
  push:
    branches:
      - main    # Triggers on any push to main branch
  pull_request:
    branches:
      - main    # Optional: Also triggers when PRs are made to main

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Push to destination repository
      env:
        GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
      run: |
        git config --global user.name 'src'
        git config --global user.email 'src.action@github.com'
        
        # Clone destination repository
        git clone https://${GITHUB_TOKEN}@github.com/cssh-it/demo1.git destination_repo
        
        # Copy all files (excluding .git)
        rsync -av --exclude='.git' ./ destination_repo/
        
        # Setup and push
        cd destination_repo
        git add .
        git commit -m "Sync from source repository - Commit: ${GITHUB_SHA}"
        git branch -M main
        git push -u origin main